# Generated by Django 5.0.6 on 2024-05-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_remember_time',
            field=models.TimeField(default='10:00'),
        ),
    ]
