# Generated by Django 5.0.6 on 2024-06-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
