# Generated by Django 5.0.6 on 2024-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0007_customer_date_choice_customer_date_time_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan_choice',
            field=models.IntegerField(default=2),
        ),
    ]
