# Generated by Django 5.0.6 on 2024-06-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0008_customer_plan_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
