# Generated by Django 5.0.6 on 2024-06-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0009_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
