# Generated by Django 5.0.6 on 2024-06-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0010_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moment_related_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_img', to='Citas.momentimage')),
            ],
        ),
    ]
