# Generated by Django 5.0.6 on 2024-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0011_momentrelatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentrelatedimage',
            name='img_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
