# Generated by Django 5.0.6 on 2024-06-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0013_alter_momentrelatedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='related_service_images/')),
                ('img_url', models.URLField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_img', to='Citas.serviceimage')),
            ],
        ),
    ]
