# Generated by Django 5.0.6 on 2024-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0015_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
