# Generated by Django 5.0.6 on 2024-06-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0016_customer_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan', max_length=255)),
                ('description', models.TextField(default='Descripción del plan')),
                ('img', models.ImageField(upload_to='media/')),
                ('price', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='momentimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='momentrelatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='servicerelatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='CaratPlanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Citas.plans')),
            ],
        ),
    ]
