# Generated by Django 5.0.6 on 2024-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0017_plans_alter_momentimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=models.TextField(blank=True, default='Descripción del plan', null=True),
        ),
    ]
