# Generated by Django 5.0.6 on 2024-06-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0018_alter_plans_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='caratplanes',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Citas.serviceimage'),
        ),
        migrations.AlterField(
            model_name='caratplanes',
            name='name',
            field=models.CharField(default='Plan o Servicio', max_length=255),
        ),
        migrations.AlterField(
            model_name='caratplanes',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Citas.plans'),
        ),
    ]
