# Generated by Django 5.0.6 on 2024-06-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0019_caratplanes_service_alter_caratplanes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratplanes',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Citas.serviceimage'),
        ),
    ]
