# Generated by Django 5.0.6 on 2024-06-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0020_alter_caratplanes_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caratplanes',
            name='service',
        ),
        migrations.AddField(
            model_name='plans',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Citas.serviceimage'),
        ),
    ]
