# Generated by Django 5.0.6 on 2024-06-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0021_remove_caratplanes_service_plans_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan_choice',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
