# Generated by Django 5.0.6 on 2024-06-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0023_customer_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='reserver_mount',
            field=models.IntegerField(default=500),
        ),
    ]
