# Generated by Django 5.0.6 on 2024-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0024_customer_reserve_customer_reserver_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reserver_mount',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
