# Generated by Django 5.0.6 on 2024-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0026_alter_customer_date_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='saled_mount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
