# Generated by Django 5.0.6 on 2024-06-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0027_customer_saled_customer_saled_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentrelatedimage',
            name='moment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moment_img', to='Citas.momentimage'),
        ),
    ]
