# Generated by Django 5.0.6 on 2024-06-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0031_remove_role_img_usera_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='Citas.role'),
        ),
    ]
