# Generated by Django 5.0.7 on 2024-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0033_permisons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisons',
            name='priori',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
