# Generated by Django 5.0.7 on 2024-08-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0035_tweet_imgtweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='p',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sub',
            field=models.CharField(default='', max_length=280),
        ),
    ]
