# Generated by Django 5.0.7 on 2024-08-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0037_imgtweet_img_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
