# Generated by Django 5.0 on 2024-09-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0039_alter_usera_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
