# Generated by Django 5.0 on 2024-09-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0040_delete_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_reserved',
            field=models.IntegerField(default=500),
        ),
    ]
