# Generated by Django 5.0 on 2024-09-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0041_customer_price_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='price_reserved',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
