# Generated by Django 5.0 on 2024-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0042_alter_customer_price_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pendiente_or',
            field=models.BooleanField(default=True),
        ),
    ]
