# Generated by Django 5.0 on 2024-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0043_customer_pendiente_or'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pendiente_or',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
