# Generated by Django 5.0 on 2024-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0044_alter_customer_pendiente_or'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pendiente_or',
        ),
        migrations.AddField(
            model_name='customer',
            name='plans_more',
            field=models.ManyToManyField(blank=True, related_name='plans_more', to='Citas.plans'),
        ),
    ]
