# Generated by Django 5.0 on 2024-10-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0045_remove_customer_pendiente_or_customer_plans_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='...')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('plans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='Citas.plans')),
            ],
        ),
    ]
