# Generated by Django 5.0 on 2024-10-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0046_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
