# Generated by Django 5.0 on 2024-10-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0047_plans_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
