# Generated by Django 5.0 on 2024-10-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0048_plans_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=100)),
                ('description', models.TextField(default='...')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adicionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_adicionales', to='Citas.plans')),
                ('plans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_plan', to='Citas.plans')),
            ],
        ),
    ]
