# Generated by Django 5.0 on 2024-10-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0049_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_service', to='Citas.plans'),
        ),
    ]
