# Generated by Django 5.0 on 2024-10-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0052_imageserviceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageserviceimg',
            name='img_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_service', to='Citas.serviceimage'),
        ),
        migrations.AlterField(
            model_name='imageserviceimg',
            name='name',
            field=models.CharField(blank=True, default='...', max_length=100, null=True),
        ),
    ]
