# Generated by Django 5.0 on 2024-10-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0053_alter_imageserviceimg_img_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentrelatedimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svc_img', to='Citas.serviceimage'),
        ),
    ]
