# Generated by Django 5.0 on 2024-10-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0059_financialrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='is_active',
            new_name='is_ingreso_or_gasto',
        ),
    ]
