# Generated by Django 5.0 on 2024-10-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0060_rename_is_active_financialrecord_is_ingreso_or_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='created_at',
            new_name='created',
        ),
    ]
