# Generated by Django 5.0 on 2024-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0061_rename_created_at_financialrecord_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='financialrecord',
            old_name='expense',
            new_name='gasto',
        ),
        migrations.RenameField(
            model_name='financialrecord',
            old_name='income',
            new_name='ingreso',
        ),
    ]
