# Generated by Django 5.0 on 2024-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0063_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
