# Generated by Django 5.0 on 2024-10-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0064_sale_price_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_sale', to='Citas.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_sale', to='Citas.plans'),
        ),
    ]
