# Generated by Django 5.0 on 2024-10-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0065_alter_sale_cliente_alter_sale_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reserve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='Citas.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Citas.plans'),
        ),
    ]
