# Generated by Django 5.0 on 2024-10-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0067_rename_estado_sale_saled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='reserve',
            new_name='reserver',
        ),
    ]
