# Generated by Django 5.0 on 2024-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0069_sale_reserver_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reserver_mount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
