# Generated by Django 5.0 on 2024-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0070_alter_sale_reserver_mount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='abonado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
