# Generated by Django 5.0 on 2024-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0072_sale_saled_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
