# Generated by Django 5.0 on 2024-11-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0073_financialrecord_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='gasto_recurrente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='renovacion_mensual_gasto_recurrente',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
