# Generated by Django 5.0 on 2024-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0074_financialrecord_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='renovacion_mensual_gasto_recurrente',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
