# Generated by Django 5.0 on 2024-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0076_packopciones_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='preci',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packopciones',
            name='preci',
            field=models.IntegerField(default=0),
        ),
    ]
