# Generated by Django 5.0 on 2024-11-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0077_opciones_preci_packopciones_preci'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saled_end',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
