# Generated by Django 5.0 on 2024-12-01 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0079_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
