# Generated by Django 5.0 on 2024-12-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0080_cashregister_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='choice_time',
            field=models.CharField(blank=True, default='10:00am', max_length=255),
        ),
    ]
