# Generated by Django 5.0 on 2024-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0081_customer_choice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='choice_time',
            field=models.CharField(blank=True, default='10:00', max_length=255),
        ),
    ]
