# Generated by Django 5.0 on 2024-12-05 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0082_alter_customer_choice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_only_choice',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
