# Generated by Django 5.0 on 2024-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0088_sale_ncf_sale_type_sale_ncf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_secuencia',
            field=models.IntegerField(default=0),
        ),
    ]
