# Generated by Django 5.0 on 2024-12-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0089_sale_sale_secuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_secuencia',
        ),
    ]
