# Generated by Django 5.0 on 2024-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0090_remove_sale_sale_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_secuencia',
            field=models.IntegerField(default=0),
        ),
    ]
