# Generated by Django 5.0 on 2024-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0091_sale_sale_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='impuestos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='itbis',
            field=models.IntegerField(default=18),
        ),
    ]
